### PR TITLE
Curious UI Initial merge

### PR DESCRIPTION
**Pull request by hntejas**

### CODE REVIEW

**Review by kajol-rep — CHANGES_REQUESTED** [review]
App looks nice. Code is clean and I like that you have used minimal code, made it so simple and documentation still looks good.

Few things from my observation I would suggest:
1. You can give space before code snippets which are positioned just after the component having no space between them or very small space.
2. In mobile mode you can replace "^" with a menu icon because I could not understand first that it is meant to open menu and thought it is just to scroll up the window. So maybe you can fix this.

**Comment by hntejas** [comment]
> App looks nice. Code is clean and I like that you have used minimal code, made it so simple and documentation still looks good.
> 
> Few things from my observation I would suggest:
> 
> 1. You can give space before code snippets which are positioned just after the component having no space between them or very small space.
> 2. In mobile mode you can replace "^" with a menu icon because I could not understand first that it is meant to open menu and thought it is just to scroll up the window. So maybe you can fix this.

Hi Kajol, thanks for reviewing the code and application

I have done the suggested changes, please let me know if they are as expected

**Review by kajol-rep — APPROVED** [review]
Yes, it looks better now. Go ahead!

**Review by themohammadsa — CHANGES_REQUESTED** [review]
Hello Tejas!

The component library looks great! The code is simple and neat.
 
I have only one suggestion functionality wise, in the mobile nav panel - could you add a back icon or a close icon as that would make the UX more cleaner.

**Comment by hntejas** [comment]
> Hello Tejas!
> 
> The component library looks great! The code is simple and neat.
> 
> I have only one suggestion functionality wise, in the mobile nav panel - could you add a back icon or a close icon as that would make the UX more cleaner.

Hi Mohammad, 

Thanks for taking time to review, I have added the required changes. Please check and let me know if it looks fine.

**Review by themohammadsa — APPROVED** [review]
Superb, Tejas! 
Everything looks good to me from my end. Go ahead for the merge.

**Pull request merged**
